version: "3.9"

services:
  backend:
    build: ./api
    container_name: armazenaai-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/armazenaai
      - NODE_ENV=development
      - JWT_SECRET=supersecreto123
    depends_on:
      - mongo
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm start

  frontend:
    build: ./web
    container_name: armazenaai-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./web:/app
    command: npm run dev -- --host

  mongo:
    image: mongo:6
    container_name: armazenaai-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
